from .BosuWorkout import BosuWorkout
from .ClassicWorkout import ClassicWorkout
from .ComboWorkout import ComboWorkout
from .FocusWorkout import FocusWorkout
from .ForgeWorkout import ForgeWorkout
from .HeartWorkout import HeartWorkout
from .SingleWorkout import SingleWorkout
from .Workout404 import Workout404
from .CoreWorkout import CoreWorkout
from .ShortWorkout import ShortWorkout
from .RunningWorkout import RunningWorkout
from .ChallengeWorkout import ChallengeWorkout